
version: '3'
services:
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: ariyan-panel
    restart: always
    ports:
      - "8080:80"
    environment:
      - APP_URL=http://localhost:8080
      - APP_TIMEZONE=Asia/Kolkata
    volumes:
      - ./panel-data:/app
